// @PortSource(file = "upstream/app/src/main/java/com/lagradost/cloudstream3/plugins/RepositoryManager.kt", upstreamCommit = "caeec18")
package com.lagradost.cloudstream3.plugins

import android.content.Context
import androidx.annotation.WorkerThread
import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty
import com.lagradost.cloudstream3.CloudStreamApp.Companion.context
import com.lagradost.cloudstream3.CloudStreamApp.Companion.getKey
import com.lagradost.cloudstream3.CloudStreamApp.Companion.setKey
import com.lagradost.cloudstream3.R
import com.lagradost.cloudstream3.amap
import com.lagradost.cloudstream3.app
import com.lagradost.cloudstream3.mvvm.logError
import com.lagradost.cloudstream3.mvvm.safe
import com.lagradost.cloudstream3.mvvm.safeAsync
import com.lagradost.cloudstream3.plugins.PluginManager.getPluginSanitizedFileName
import com.lagradost.cloudstream3.plugins.PluginManager.unloadPlugin
import com.lagradost.cloudstream3.ui.settings.extensions.REPOSITORIES_KEY
import com.lagradost.cloudstream3.ui.settings.extensions.RepositoryData
import kotlinx.coroutines.sync.Mutex
import kotlinx.coroutines.sync.withLock
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import java.io.File
import java.nio.file.AtomicMoveNotSupportedException
import java.nio.file.Files
import java.nio.file.StandardCopyOption
import java.security.MessageDigest
import java.util.concurrent.TimeUnit

/**
 * Comes with the app, always available in the app, non removable.
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Serializable
data class Repository(
    @JsonProperty("iconUrl") @SerialName("iconUrl") val iconUrl: String? = null,
    @JsonProperty("name") @SerialName("name") val name: String,
    @JsonProperty("description") @SerialName("description") val description: String? = null,
    @JsonProperty("manifestVersion") @SerialName("manifestVersion") val manifestVersion: Int = 1,
    @JsonProperty("pluginLists") @SerialName("pluginLists") val pluginLists: List<String> = emptyList(),
)

/**
 * Status int as the following:
 * 0: Down
 * 1: Ok
 * 2: Slow
 * 3: Beta only
 */
@JsonIgnoreProperties(ignoreUnknown = true)
@Serializable
data class SitePlugin(
    // Url to the .cs3 file
    @JsonProperty("url") @SerialName("url") val url: String,
    // Status to remotely disable the provider
    @JsonProperty("status") @SerialName("status") val status: Int = 1,
    // Integer over 0, any change of this will trigger an auto update
    @JsonProperty("version") @SerialName("version") val version: Int = 1,
    // Unused currently, used to make the api backwards compatible?
    // Set to 1
    @JsonProperty("apiVersion") @SerialName("apiVersion") val apiVersion: Int = 1,
    // Name to be shown in app
    @JsonProperty("name") @SerialName("name") val name: String,
    // Name to be referenced internally. Separate to make name and url changes possible
    @JsonProperty("internalName") @SerialName("internalName") val internalName: String,
    @JsonProperty("authors") @SerialName("authors") val authors: List<String> = emptyList(),
    @JsonProperty("description") @SerialName("description") val description: String? = null,
    // Might be used to go directly to the plugin repo in the future
    @JsonProperty("repositoryUrl") @SerialName("repositoryUrl") val repositoryUrl: String? = null,
    // These types are yet to be mapped and used, ignore for now
    @JsonProperty("tvTypes") @SerialName("tvTypes") val tvTypes: List<String>? = null,
    // Most often a language tag like "en" or "zh-TW"
    @JsonProperty("language") @SerialName("language") val language: String? = null,
    @JsonProperty("iconUrl") @SerialName("iconUrl") val iconUrl: String? = null,
    // Automatically generated by the gradle plugin
    @JsonProperty("fileSize") @SerialName("fileSize") val fileSize: Long? = null,
    @JsonProperty("fileHash") @SerialName("fileHash") val fileHash: String? = null,
    @JsonProperty("jarUrl") @SerialName("jarUrl") val jarUrl: String? = null,
)

@JsonIgnoreProperties(ignoreUnknown = true)
@Serializable
data class PluginWrapper(
    @JsonProperty("repository") @SerialName("repository") val repository: Repository,
    @JsonProperty("repositoryData") @SerialName("repositoryData") val repositoryData: RepositoryData,
    @JsonProperty("plugin") @SerialName("plugin") val plugin: SitePlugin
) {
    companion object {
        private val localRepository = Repository("", "", "", 1, emptyList())
        private val localRepositoryData = RepositoryData("", "", "")
        fun getLocalPluginWrapper(plugin: SitePlugin): PluginWrapper {
            return PluginWrapper(
                localRepository,
                localRepositoryData,
                plugin
            )
        }
    }
}

object RepositoryManager {
    const val ONLINE_PLUGINS_FOLDER = "Extensions"
    val PREBUILT_REPOSITORIES: Array<RepositoryData> by lazy {
        getKey<Array<RepositoryData>>("PREBUILT_REPOSITORIES") ?: emptyArray()
    }
    private val GH_REGEX =
        Regex("^https://raw.githubusercontent.com/([A-Za-z0-9-]+)/([A-Za-z0-9_.-]+)/(.*)$")

    /** Returns a SHA-256 string of the file content.
     * Example: "sha256-b70462c264cb7f90fc2860a8e58d7544ce747ff347d1d11fa093623901853573" **/
    @WorkerThread
    fun sha256(file: File): String {
        val digest = MessageDigest.getInstance("SHA-256")

        file.inputStream().use { fis ->
            val buffer = ByteArray(8192)
            var read = fis.read(buffer)
            while (read != -1) {
                digest.update(buffer, 0, read)
                read = fis.read(buffer)
            }
        }
        return "sha256-" + digest.digest().joinToString("") { "%02x".format(it) }
    }

    /* Convert raw.githubusercontent.com urls to cdn.jsdelivr.net if enabled in settings */
    fun convertRawGitUrl(url: String, force: Boolean = false): String {
        val proxyKey = context?.getString(R.string.jsdelivr_proxy_key) ?: "jsdelivr_proxy_key"
        if (!force && getKey<Boolean>(proxyKey) != true) return url
        val match = GH_REGEX.find(url) ?: return url
        val (user, repo, rest) = match.destructured
        return "https://cdn.jsdelivr.net/gh/$user/$repo@$rest"
    }

    suspend fun parseRepoUrl(url: String): String? {
        val fixedUrl = url.trim()
        return if (fixedUrl.contains("^https?://".toRegex())) {
            fixedUrl
        } else if (fixedUrl.contains("^(cloudstreamrepo://)|(https://cs\\.repo/\\??)".toRegex())) {
            fixedUrl.replace("^(cloudstreamrepo://)|(https://cs\\.repo/\\??)".toRegex(), "").let {
                return@let if (!it.contains("^https?://".toRegex()))
                    "https://${it}"
                else fixedUrl
            }
        } else if (fixedUrl.matches("^[a-zA-Z0-9!_-]+$".toRegex())) {
            safeAsync {
                val isPyMd = fixedUrl.startsWith("!")
                val targetUrl = if (isPyMd) {
                    "https://py.md/${fixedUrl.removePrefix("!")}"
                } else {
                    "https://cutt.ly/$fixedUrl"
                }
                val response = app.get(targetUrl, allowRedirects = false)
                val location = response.headers["Location"] ?: return@safeAsync null
                var loc = location
                if (loc.startsWith("/")) {
                    loc = if (isPyMd) "https://py.md$loc" else "https://cutt.ly$loc"
                }
                if (isPyMd) {
                    if (loc.startsWith("https://py.md/404") || loc.removeSuffix("/") == "https://py.md" || loc.endsWith("/404")) return@safeAsync null
                    return@safeAsync loc
                } else {
                    if (loc.startsWith("https://cutt.ly/404") || loc.removeSuffix("/") == "https://cutt.ly" || loc.endsWith("/404")) return@safeAsync null
                    return@safeAsync loc
                }
            }
        } else null
    }

    suspend fun parseRepository(url: String): Repository? {
        return safeAsync {
            // Take manifestVersion and such into account later
            app.get(convertRawGitUrl(url), cacheTime = 5, cacheUnit = TimeUnit.MINUTES)
                .parsedSafe<Repository>()
        }
    }

    private suspend fun parsePlugins(pluginUrls: String): List<SitePlugin> {
        // Take manifestVersion and such into account later
        return try {
            app.get(convertRawGitUrl(pluginUrls), cacheTime = 5, cacheUnit = TimeUnit.MINUTES)
                .parsed<Array<SitePlugin>>().toList()
        } catch (t: Throwable) {
            logError(t)
            emptyList()
        }
    }

    /**
     * Gets all plugins from repositories and pairs them with the repository url
     */
    suspend fun getRepoPlugins(repositoryData: RepositoryData): List<PluginWrapper>? {
        val repo = parseRepository(repositoryData.url) ?: return null
        val list = repo.pluginLists.amap { url ->
            parsePlugins(url).map {
                PluginWrapper(repo, repositoryData, it)
            }
        }.flatten()
        return list
    }

    suspend fun downloadPluginToFile(
        context: Context,
        pluginUrl: String,
        file: File,
        expectedFileHash: String?
    ): File? {
        return safeAsync {
            val parentDir = file.parentFile ?: return@safeAsync null
            parentDir.mkdirs()

            // Prevent corrupting the plugin file if the operation fails
            val cacheDir = context.cacheDir ?: File(System.getProperty("java.io.tmpdir", "/tmp"))
            val tempFile = File.createTempFile(file.name, ".tmp", cacheDir)

            val body = app.get(convertRawGitUrl(pluginUrl)).okhttpResponse.body
                ?: throw IllegalStateException("Empty response body from $pluginUrl")

            body.byteStream().use { bodyStream ->
                tempFile.outputStream().use { fileStream ->
                    bodyStream.copyTo(fileStream)
                }
            }

            if (expectedFileHash != null) {
                val downloadHash = sha256(tempFile)
                if (expectedFileHash != downloadHash) {
                    tempFile.delete()
                    throw IllegalStateException("Extension hash mismatch when validating '${file.name}'! Expected: '$expectedFileHash', got: '$downloadHash'.")
                }
            }

            // We prefer the operation to be atomic
            try {
                Files.move(
                    tempFile.toPath(),
                    file.toPath(),
                    StandardCopyOption.REPLACE_EXISTING,
                    StandardCopyOption.ATOMIC_MOVE
                )
            } catch (_: AtomicMoveNotSupportedException) {
                Files.move(
                    tempFile.toPath(),
                    file.toPath(),
                    StandardCopyOption.REPLACE_EXISTING
                )
            }

            file
        }
    }

    fun getRepositories(): Array<RepositoryData> {
        return getKey<Array<RepositoryData>>(REPOSITORIES_KEY) ?: emptyArray()
    }

    // Don't want to read before we write in another thread
    private val repoLock = Mutex()
    suspend fun addRepository(repository: RepositoryData) {
        repoLock.withLock {
            val currentRepos = getRepositories()
            // No duplicates
            setKey(REPOSITORIES_KEY, (currentRepos + repository).distinctBy { it.url }.toTypedArray())
        }
    }

    /**
     * Also deletes downloaded repository plugins
     */
    suspend fun removeRepository(context: Context, repository: RepositoryData) {
        val extensionsDir = File(context.filesDir, ONLINE_PLUGINS_FOLDER)

        repoLock.withLock {
            val currentRepos = getKey<Array<RepositoryData>>(REPOSITORIES_KEY) ?: emptyArray()
            // No duplicates
            val newRepos = currentRepos.filter { it.url != repository.url }.toTypedArray()
            setKey(REPOSITORIES_KEY, newRepos)
        }

        val file = File(
            extensionsDir,
            getPluginSanitizedFileName(repository.url)
        )

        // Unload all plugins, not using deletePlugin since we
        // delete all data and files in deleteRepositoryData
        safe {
            file.listFiles(java.io.FileFilter { plugin: File ->
                unloadPlugin(plugin.absolutePath)
                false
            })
        }

        PluginManager.deleteRepositoryData(file.absolutePath)
    }
}
